UIPFAUTH-3:
folio-org/ui-plugin-find-authority pull request #15
Opened 2022-08-17 11:30 UTC by Dmytro-Melnyshyn

## Purpose 
fix advanced search, pagination, list and filter visibility described in comments;

## Issues
[UIPFAUTH-3](https://issues.folio.org/browse/UIPFAUTH-3)

## Screencast

https://user-images.githubusercontent.com/77053927/185107766-746f5b65-f44b-43f2-9bef-b133e812658d.mp4

2022-08-18 10:57 UTC, BogdanDenis requested changes

2022-08-18 10:57 UTC, BogdanDenis commented on test/jest/turn-off-warnings.js
> +  /Warning: Failed %s type: %s%s/,
Same as comment in `stripes-authority-components` - created a ticket to fix props in tests
https://issues.folio.org/browse/UIPFAUTH-10

2022-08-19 07:11 UTC, BogdanDenis approved these changes

2022-08-19 08:44 UTC, odoniyor approved these changes

2022-08-19 19:08 UTC, merged